/*!40000 ALTER TABLE `alerta` DISABLE KEYS */;
/*!40000 ALTER TABLE `alerta` ENABLE KEYS */;
/*!40000 ALTER TABLE `configuracaolabirinto` DISABLE KEYS */;
INSERT INTO `configuracaolabirinto` VALUES (15.00,30,10);
/*!40000 ALTER TABLE `configuracaolabirinto` ENABLE KEYS */;
/*!40000 ALTER TABLE `corredor` DISABLE KEYS */;
/*!40000 ALTER TABLE `corredor` ENABLE KEYS */;
/*!40000 ALTER TABLE `erroexperiencia` DISABLE KEYS */;
/*!40000 ALTER TABLE `erroexperiencia` ENABLE KEYS */;
/*!40000 ALTER TABLE `experiencia` DISABLE KEYS */;
/*!40000 ALTER TABLE `experiencia` ENABLE KEYS */;
/*!40000 ALTER TABLE `log` DISABLE KEYS */;
/*!40000 ALTER TABLE `log` ENABLE KEYS */;
/*!40000 ALTER TABLE `medicaopassagem` DISABLE KEYS */;
/*!40000 ALTER TABLE `medicaopassagem` ENABLE KEYS */;
/*!40000 ALTER TABLE `medicaosala` DISABLE KEYS */;
/*!40000 ALTER TABLE `medicaosala` ENABLE KEYS */;
/*!40000 ALTER TABLE `medicaotemperatura` DISABLE KEYS */;
/*!40000 ALTER TABLE `medicaotemperatura` ENABLE KEYS */;
/*!40000 ALTER TABLE `odor` DISABLE KEYS */;
/*!40000 ALTER TABLE `odor` ENABLE KEYS */;
/*!40000 ALTER TABLE `odorexperiencia` DISABLE KEYS */;
/*!40000 ALTER TABLE `odorexperiencia` ENABLE KEYS */;
/*!40000 ALTER TABLE `parametrosadicionais` DISABLE KEYS */;
INSERT INTO `parametrosadicionais` VALUES ('FATOR_ALERTA_TEMPERATURA','1','0.8','Fator \'valor\' que determina quando um alerta vermelho é lançado para temperatura T tal que T > tempIdeal+valor*varTemp ou T < tempIdeal-valor*varTemp'),('FATOR_ALERTA_TEMPERATURA','2','0.6','Fator \'valor\' que determina quando um alerta laranja é lançado para temperatura T tal que T > tempIdeal+valor*varTemp ou T < tempIdeal-valor*varTemp'),('FATOR_ALERTA_TEMPERATURA','3','0.5','Fator \'valor\' que determina quando um alerta amarelo é lançado para temperatura T tal que T > tempIdeal+valor*varTemp ou T < tempIdeal-valor*varTemp'),('NUM_MAX_ALERTA','1','3','Número máximo de alertas (3) para o Tipo de Alerta (1)'),('NUM_MAX_ALERTA','2','2','Número máximo de alertas (2) para o Tipo de Alerta (2)'),('NUM_MAX_ALERTA','3','1','Número máximo de alertas (1) para o Tipo de Alerta (3)'),('NUM_MAX_ALERTA','4','1','Número máximo de alertas (1) para o Tipo de Alerta (4)'),('NUM_MAX_ALERTA','5','1','Número máximo de alertas (1) para o Tipo de Alerta (5)'),('NUM_MAX_ALERTA','6','1','Número máximo de alertas (1) para o Tipo de Alerta (6)'),('NUM_MAX_ALERTA','TEMPO','120','Numero máximo de alerta no intervalo de VALOR expresso em segundos'),('NUM_MAX_SENSORES','NUM_SENSORES','2','Numero maximo de sensores no labirinto. Os sensores terão a nomecultura de \'1\' até ao numero maximo de sensores. Este numero deve ser >0'),('NUM_MIN_ERROS','NUM_ERROS','3','Número mínimo de erros inseridos na tabela erroexperiencia para despoletar a tentativa de alerta'),('PARAMETRO_PERIODICIDADE','FATOR','4','Fator multiplicativo de proporcionalidade direta em relação à periodicidade, sem que esta consiga exceder TEMPO maximo de periodicidade. Enquanto maior este numero, mais rapido a periodicidade se aproxima do tempo maximo permitido em função de SegundosAberturaPortasExterior'),('PARAMETRO_PERIODICIDADE','TEMPO','120','Tempo máximo entre cada receção de dados do mongo, em segundos'),('TAMANHO_OUTLIER_SAMPLE','FATOR','0.5','O tamanho máximo de uma amostra para calculo de outliers é calculado através da formula fator*segundosaberturaportaexterior*dadosporsegundo. Este valor deve estar em ]0,1['),('TEMPERATURA','MAXIMA','60','Temperatura máxima admitida no ambito de uma experiencia'),('TEMPERATURA','MINIMA','5','Temperatura minima admitida no ambito de uma experiencia'),('TEMPO_CHECK_FINS','TEMPO','15','Tempo entre verificações de final de experiências em segundos'),('TEMPO_ENTRE_CHECK_MOVIMENTO','TEMPO','5','Verificar se o tempo sem movimento dos ratos da ultima experiencia a ocorrer de [valor] em [valor] segundos.'),('TEMPO_ENTRE_EXPERIENCIA','TEMPO','10','Tempo minimo entre experiencias em minutos.');
/*!40000 ALTER TABLE `parametrosadicionais` ENABLE KEYS */;
/*!40000 ALTER TABLE `substancia` DISABLE KEYS */;
/*!40000 ALTER TABLE `substancia` ENABLE KEYS */;
/*!40000 ALTER TABLE `substanciaexperiencia` DISABLE KEYS */;
/*!40000 ALTER TABLE `substanciaexperiencia` ENABLE KEYS */;
/*!40000 ALTER TABLE `tipoalerta` DISABLE KEYS */;
INSERT INTO `tipoalerta` VALUES (1,'Alerta Vermelho',NULL),(2,'Alerta Laranja',NULL),(3,'Alerta Amarelo',NULL),(4,'Limite Ratos',NULL),(5,'Segundos Sem Movimento',NULL),(6,'Erros de dados',NULL);
/*!40000 ALTER TABLE `tipoalerta` ENABLE KEYS */;
/*!40000 ALTER TABLE `tipoutilizador` DISABLE KEYS */;
INSERT INTO `tipoutilizador` VALUES ('AppAdmin'),('Investigador'),('Java'),('Tecnico');
/*!40000 ALTER TABLE `tipoutilizador` ENABLE KEYS */;
/*!40000 ALTER TABLE `utilizador` DISABLE KEYS */;
/*!40000 ALTER TABLE `utilizador` ENABLE KEYS */;
