# Generated by Django 4.2 on 2023-05-13 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=50)),
                ('Imagem', models.CharField(max_length=250)),
                ('Stock', models.IntegerField(default=0)),
                ('Preco_Unidade', models.FloatField()),
                ('Descricao', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data', models.DateTimeField()),
                ('PrecoTotal', models.FloatField()),
                ('EnderecoAlternativo', models.CharField(max_length=150)),
                ('Pago', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User_Extension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Imagem', models.CharField(max_length=250)),
                ('Ativo', models.BooleanField(default=True)),
                ('Endereco', models.CharField(max_length=150)),
                ('Phone', models.CharField(max_length=15)),
                ('Tipo', models.CharField(choices=[('CL', 'Cliente'), ('AA', 'Appadmin'), ('EM', 'Empregado')], default='CL', max_length=2)),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('is_app_admin', 'Is an application administrator.'), ('is_employee', 'Is a employee.'), ('is_client', 'Is a client.')],
            },
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data', models.DateTimeField()),
                ('Preco_Total', models.FloatField()),
                ('Enviado', models.BooleanField(default=False)),
                ('Endereco_Venda', models.CharField(max_length=150)),
                ('Cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.user_extension')),
                ('Reserva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.reserva')),
            ],
        ),
        migrations.AddField(
            model_name='reserva',
            name='Cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.user_extension'),
        ),
        migrations.CreateModel(
            name='Encomenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data', models.DateTimeField()),
                ('Preco_Total', models.FloatField()),
                ('Recibo', models.IntegerField()),
                ('Recebido', models.BooleanField(default=False)),
                ('Solicitador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.user_extension')),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantidade', models.IntegerField()),
                ('Produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.produto')),
                ('Venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.venda')),
            ],
            options={
                'unique_together': {('Venda', 'Produto')},
            },
        ),
        migrations.CreateModel(
            name='ProdutoReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantidade', models.IntegerField()),
                ('Produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.produto')),
                ('Reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.reserva')),
            ],
            options={
                'unique_together': {('Produto', 'Reserva')},
            },
        ),
        migrations.CreateModel(
            name='ProdutoEncomenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantidade', models.IntegerField()),
                ('Preco_Unidade', models.FloatField(default=0)),
                ('Encomenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.encomenda')),
                ('Produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.produto')),
            ],
            options={
                'unique_together': {('Encomenda', 'Produto')},
            },
        ),
    ]
